# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TakeHomeChallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'CSV.swift', '~> 2.3.1'
  
  # Pods for TakeHomeChallenge
  target 'TakeHomeChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TakeHomeChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
